
import { useEffect, useState } from 'react';
import { Code2, GitBranch, Briefcase, Mail, Download, Menu, X, Layers, ShieldCheck, Database, MapPin, Plus, Minus, Check, Copy } from 'lucide-react';

const stacks = ['Java', 'Spring Boot', 'React', 'TypeScript', 'MySQL', 'Docker'];
const work = [
 {name:'Bancassurance System',type:'FINANCIAL SERVICES',body:'Secure business workflows built for enterprise operations.',detail:'Developed REST APIs, JWT authentication and role-based authorization with Spring Security. Designed JPA/Hibernate persistence and transactional workflows, alongside SMS notifications and business reporting.',tags:['Spring Boot','Spring Security','JPA / Hibernate']},
 {name:'Contract Farming System',type:'AGRICULTURE',body:'Backend services connecting business requirements to daily operations.',detail:'Developed Spring Boot APIs and database structures, collaborated on Angular integration, and delivered application enhancements and production fixes.',tags:['Spring Boot','Angular','REST APIs']},
 {name:'eTIN System',type:'ENTERPRISE APPLICATION',body:'Maintainable backend modules and reporting workflows.',detail:'Developed and maintained layered Spring Boot modules and REST APIs, implemented reporting features, and resolved production issues.',tags:['Java','Spring Boot','Reporting']},
 {name:'Dealer Wallet',type:'AUTOMOTIVE OPERATIONS',body:'An internal platform for dealer, sales and inventory operations.',detail:'Designed and developed an enterprise application at TVS Auto Bangladesh with .NET and jQuery. Built RDLC reports and provided maintenance, production support and enhancements.',tags:['.NET','jQuery','RDLC']},
];
export default function Home(){
 const [menu,setMenu]=useState(false); const [open,setOpen]=useState<number|null>(null); const [copied,setCopied]=useState(false);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 async function copy(){try{await navigator.clipboard.writeText('azizularif94@gmail.com');setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{window.location.href='mailto:azizularif94@gmail.com'}}
 return <><a className="skip" href="#main">Skip to content</a><header className="site-header"><div className="wrap flex items-center justify-between gap-6"><a href="#" className="brand" aria-label="Azizul home">a<span>.</span></a><nav aria-label="Main navigation" className={menu?'nav open':'nav'}>{['About','Work','Experience','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}</nav><a className="header-contact" href="mailto:azizularif94@gmail.com">Let’s talk <Mail size={15}/></a><button className="menu-btn" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="main"><section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="tiny-line"/> SOFTWARE ENGINEER · DHAKA, BD</div><p className="intro">Hi, I’m Azizul.</p><h1>Thoughtful code.<br/>Reliable systems.<br/><span>Real impact.</span></h1><p className="hero-description">I build secure, scalable web applications with Java, Spring Boot and React. From the API to the interface, I care about getting the details right.</p><div className="flex flex-wrap gap-3"><a className="button primary" href="#work">Explore my work</a><a className="button secondary" href={`${import.meta.env.BASE_URL}Azizul-Islam-CV.pdf`} download><Download size={17}/> Download CV</a></div><div className="hero-socials"><a href="https://github.com/Azizul-arif" target="_blank" rel="noreferrer"><GitBranch size={18}/> GitHub</a><a href="https://www.linkedin.com/in/azizul-arif-494912199" target="_blank" rel="noreferrer"><Briefcase size={18}/> LinkedIn</a><span><MapPin size={16}/> Dhaka, Bangladesh</span></div></div>
 <div className="hero-visual" aria-label="Core engineering expertise"><div className="visual-top"><span>THE ENGINEERING MINDSET</span><Code2 size={20}/></div><div className="monogram">a<span>.</span></div><div className="code-caption"><span className="code-purple">build</span>({'{'}<br/><span className="code-indent">secure: <b>true</b>,</span><br/><span className="code-indent">maintainable: <b>true</b>,</span><br/><span className="code-indent">purpose: <i>“people”</i></span><br/>{'}'});</div><div className="visual-bottom"><span>BACKEND LOGIC.<br/>FRONTEND CLARITY.</span><span className="visual-cross">+</span></div><div className="experience-float"><strong>4+</strong><span>YEARS OF<br/>EXPERIENCE</span></div></div></section>
 <div className="stack-strip"><div className="wrap flex flex-wrap items-center justify-between gap-6"><span className="stack-label">MY EVERYDAY TOOLKIT</span>{stacks.map(s=><span key={s} className="stack-name">{s}</span>)}</div></div>
 <section id="about" className="wrap section reveal"><div className="section-label">01 / ABOUT</div><div className="about-grid"><h2>Built on curiosity.<br/><span>Driven by craft.</span></h2><div><p className="large-copy">I’m Md Azizul Islam, a software engineer who enjoys turning complex business requirements into clear, dependable software.</p><p className="muted mt-5">My work spans enterprise systems, secure APIs and full-stack applications. I bring hands-on experience with Spring Security, relational data modeling and production support, grounded in SOLID principles and Agile collaboration.</p><div className="about-values"><span><ShieldCheck/> Security by design</span><span><Layers/> Clean architecture</span><span><Database/> Reliable data</span></div></div></div></section>
 <section id="work" className="work-section"><div className="wrap section"><div className="section-label reveal">02 / SELECTED WORK</div><div className="section-title reveal"><h2>Engineering in action<span>.</span></h2><p>Personal projects. Enterprise experience.</p></div><article className="featured reveal"><div className="feature-copy"><div className="eyebrow">FEATURED PERSONAL PROJECT</div><h3>FlowOps<span>.</span></h3><p className="feature-subtitle">Structure for teams.<br/>Security at every layer.</p><p>A full-stack, role-based task management and workflow platform. Built to connect people, projects and day-to-day work with clear access controls.</p><div className="tags">{['Spring Boot','React','JWT','MySQL','Docker'].map(t=><span key={t}>{t}</span>)}</div><a className="button primary" href="https://github.com/Azizul-arif/FlowOps" target="_blank" rel="noreferrer"><GitBranch size={18}/> Explore on GitHub</a></div><div className="architecture"><div className="architecture-head"><span className="flow-logo"><Layers size={18}/> FlowOps</span><span>ARCHITECTURE OVERVIEW</span></div><div className="architecture-layer"><span className="layer-number">01</span><div><strong>React frontend</strong><small>Redux Toolkit Query · User workflows</small></div><Code2/></div><div className="connector-line"/><div className="architecture-layer"><span className="layer-number">02</span><div><strong>Secure API layer</strong><small>Spring Security · JWT · Role-based access</small></div><ShieldCheck/></div><div className="connector-line"/><div className="architecture-layer"><span className="layer-number">03</span><div><strong>Business & persistence</strong><small>Services · JPA / Hibernate · MySQL</small></div><Database/></div><div className="architecture-foot"><span>Users & roles</span><span>Projects & tasks</span><span>Comments & history</span></div></div></article>
 <div className="project-grid">{work.map((p,i)=><article className="project-card reveal" key={p.name}><div className="flex items-center justify-between"><span className="eyebrow">{p.type}</span><span className="project-number">0{i+1}</span></div><h3>{p.name}</h3><p>{p.body}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><button className="detail-button" onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i} aria-controls={'detail-'+i}>{open===i?'Hide contributions':'My contributions'}{open===i?<Minus size={17}/>:<Plus size={17}/>}</button><div id={'detail-'+i} hidden={open!==i} className="project-detail">{p.detail}</div></article>)}</div></div></section>
 <section id="experience" className="wrap section reveal"><div className="section-label">03 / EXPERIENCE</div><div className="experience-grid"><div><h2>A steady focus.<br/><span>A growing journey.</span></h2><p className="muted mt-5">Building, collaborating and improving<br className="hidden md:block"/> with every release.</p></div><div className="timeline"><article><div className="timeline-date">FEB 2024 — PRESENT</div><h3>Software Engineer</h3><div className="company">Synesis IT</div><p>Developing Spring Boot enterprise applications across bancassurance, contract farming and eTIN. Contributing to secure APIs, data architecture, code reviews and production support.</p><div className="tags"><span>Java & Spring Boot</span><span>Enterprise systems</span></div></article><article><div className="timeline-date">AUG 2021 — JAN 2024</div><h3>Executive, Software Development</h3><div className="company">TVS Auto Bangladesh</div><p>Built and maintained Dealer Wallet, supporting dealer operations, sales, inventory and business reporting.</p><div className="tags"><span>.NET</span><span>Business applications</span></div></article><article className="education"><div className="timeline-date">EDUCATION · 2019</div><h3>B.Sc. in Computer Science & Engineering</h3><p>United International University</p></article></div></div></section>
 <section className="skills-section"><div className="wrap section reveal"><div className="section-label">04 / TECHNICAL TOOLBOX</div><h2>The tools behind the work<span>.</span></h2><div className="skills-grid">{[['Backend & architecture','Java','Spring Boot / MVC','Spring Security & JWT','REST APIs','JPA / Hibernate','Microservices'],['Frontend','React','TypeScript / JavaScript','Redux Toolkit Query','Angular','Tailwind CSS','Material UI'],['Data & delivery','MySQL / PostgreSQL','SQL Server','Docker','Git / GitHub','Maven','Swagger / OpenAPI'],['Engineering practices','SOLID principles','System design','Design patterns','Agile / Scrum','Requirement analysis','Production support']].map(group=><div key={group[0]}><h3>{group[0]}</h3>{group.slice(1).map(t=><p key={t}>{t}</p>)}</div>)}</div></div></section>
 <section id="contact" className="wrap section contact reveal"><div className="section-label">05 / GET IN TOUCH</div><div className="contact-grid"><h2>Have something<br/>worth building<span>?</span></h2><div><p>I’m always happy to connect about software engineering, interesting projects and opportunities to make useful things.</p><a className="email-link" href="mailto:azizularif94@gmail.com">azizularif94@gmail.com</a><div className="flex flex-wrap gap-3"><a className="button primary" href="mailto:azizularif94@gmail.com"><Mail size={17}/> Say hello</a><button className="button secondary" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}<span aria-live="polite">{copied?'Email copied':'Copy email'}</span></button></div></div></div></section></main><footer className="wrap"><a className="brand" href="#">a<span>.</span></a><span>© {new Date().getFullYear()} Md Azizul Islam</span><div><a href="https://github.com/Azizul-arif" target="_blank" rel="noreferrer">GitHub</a><a href="https://www.linkedin.com/in/azizul-arif-494912199" target="_blank" rel="noreferrer">LinkedIn</a><a href="#main">Back to top</a></div></footer></>
}
